# This file is part of MakeWebGallery.
#
# MakeWebGallery is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MakeWebGallery is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with MakeWebGallery.  If not, see <http://www.gnu.org/licenses/>.

import os.path

TEMPLATES_DIR = os.path.join(
    os.path.dirname(__file__),
    'templates',
)
assert not isinstance(TEMPLATES_DIR, bytes)

AUTO_GENERATED_COMMENT = [
    'This file was auto-generated by utility MakeWebGallery',
    '<https://launchpad.net/2011-01-04.make-web-gallery>.',
    '',
    'PLEASE DO NOT EDIT THIS FILE,',
    'changes will be overwritten the next time the utility is run.',
]

ITEMS_JS_BASENAME = 'items.js'
ITEMS_JS_IN_FILENAME = os.path.join(
    TEMPLATES_DIR,
    '%s.in' % ITEMS_JS_BASENAME,
)
ITEMS_JS_IN_ELEMENT_FILENAME = os.path.join(
    TEMPLATES_DIR,
    'elem.%s.in' % ITEMS_JS_BASENAME,
)
ITEMS_JS_IN_ELEMENT_JOINER = '\n'

STATIC_HTML_BASENAME = 'static_%s.xhtml'
STATIC_HTML_IN_FILENAME = os.path.join(
    TEMPLATES_DIR,
    '%s.in' % (STATIC_HTML_BASENAME),
)
STATIC_HTML_IN_ELEMENT_FILENAME = os.path.join(
    TEMPLATES_DIR,
    'elem.%s.in' % (STATIC_HTML_BASENAME),
)
STATIC_HTML_IN_PAGE_MENU_ELEMENT_FILENAME = os.path.join(
    TEMPLATES_DIR,
    'page_menu_elem.%s.in' % (STATIC_HTML_BASENAME),
)
STATIC_HTML_IN_ELEMENT_JOINER = '\n'
STATIC_HTML_IN_PAGE_MENU_ELEMENT_JOINER = ',\n'
STATIC_HTML_PAGE_LEN = 50

